import { Header } from "@/components/Header";
import "./globals.css";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Mercado Libre",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body
        className={`${montserrat.className}  bg-gray-100 min-h-screen w-screen`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
